[tool.poetry]
name = "rag-aerospike"
version = "0.0.1"
description = "RAG using Aerospike Vector Search"
authors = [
    "Dylan Welch <dwelch@aerospike.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain-core = ">=0.1.5,<0.3"
aerospike-vector-search = ">=1.0.0"
pypdf = ">=4.3.1"
langchain-openai = ">=0.0.1"
langchain-huggingface = ">=0.0.1"
langchain-community = ">=0.2.12"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "rag_aerospike"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Aerospike"
integrations = ["Aerospike", "HuggingFace", "OpenAI"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
